name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Check for formatting issues with Prettier
      - name: Run Prettier check
        run: npx prettier --check .

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint, format]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project (optional step for production, you can remove if not needed)
      - name: Build project
        run: npm run build

      # Debugging step to ensure .next exists (remove if not building)
      - name: List .next folder contents (optional)
        run: ls -la .next

      # Setup SSH to deploy to VDS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VDS_PRIVATE_KEY }}

      # Copy files to the server
      - name: Deploy to VDS
        run: |
          # Create the deploy directory on the VDS server
          ssh -o StrictHostKeyChecking=no ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }} "mkdir -p ${{ secrets.VDS_DEPLOY_PATH }}"

          # Use rsync to transfer files, excluding large/unnecessary directories
          rsync -avz --exclude='node_modules' --exclude='.git' --exclude='.next' . ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }}:${{ secrets.VDS_DEPLOY_PATH }}/

          # SSH into the server to run npm install and pm2 start/restart
          ssh -o StrictHostKeyChecking=no ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }} "
            cd ${{ secrets.VDS_DEPLOY_PATH }} &&
            npm install --production &&
            pm2 restart app || pm2 start npm --name app -- dev
          "
